import type { Metadata } from "next";
import Link from "next/link";
import { Reveal } from "@/components/reveal";

export const metadata: Metadata = { title: "Student Guide", description: "A student guide to FIRST Robotics Competition and the RobotECS season." };
const facts = [["DESIGN","Turn a game challenge into a robot strategy."],["BUILD","Prototype, test, and refine mechanical systems."],["CODE","Program controls and autonomous behavior."],["COMPETE","Work with other teams at official FRC events."]];
export default function StudentPage(){return <main id="main">
  <section className="editorial-hero"><p className="eyebrow">FRC TEAM 12394 / STUDENT GUIDE</p><Reveal><h1>YOUR FIRST<br/><span className="text-primary">SEASON.</span></h1><p>Meet RobotECS, our official FRC team, and see what students learn together during a competition season.</p></Reveal></section>
  <section className="grid gap-12 bg-white px-5 py-28 text-black md:grid-cols-[.35fr_1.65fr] md:px-[8vw]"><p className="eyebrow">01 / WHAT IS FRC?</p><Reveal><h2 className="text-5xl font-bold tracking-[-.06em] md:text-7xl">Sport-level energy.<br/>Engineering-level work.</h2><p className="mt-8 max-w-3xl text-lg leading-relaxed text-zinc-700">FIRST Robotics Competition is a high-school program where students design, build, and program an industrial-sized robot for a new game released each January.</p></Reveal></section>
  <section className="px-5 py-28 md:px-[8vw]"><Reveal><p className="eyebrow">02 / THE TEAM EXPERIENCE</p></Reveal><div className="mt-14 grid gap-8 md:grid-cols-4">{facts.map(([value,copy], index)=><Reveal key={value} delay={index * 90}><article className="border-t border-white/20 pt-5"><strong className="text-3xl tracking-[-.06em] md:text-4xl">{value}</strong><p className="mt-4 text-sm leading-relaxed text-muted-foreground">{copy}</p></article></Reveal>)}</div></section>
  <section className="grid gap-12 bg-primary px-5 py-28 text-white md:grid-cols-[.75fr_1.25fr] md:px-[8vw]"><Reveal><p className="eyebrow text-white">03 / THIS SEASON</p><h2 className="mt-6 text-6xl font-bold tracking-[-.07em]">What will we build?</h2></Reveal><Reveal delay={120}><p className="text-xl leading-relaxed">After Kickoff, we will study the rules, prototype several mechanisms, choose a drive base and scoring strategy, then build the robot that our team can operate reliably.</p></Reveal></section>
  <section className="px-5 py-28 md:px-[8vw]"><Reveal><p className="eyebrow">READY?</p><h2 className="mt-6 text-6xl font-bold tracking-[-.07em] md:text-8xl">Bring a question.<br/><span className="text-primary">Leave with a skill.</span></h2><Link href="/contact" className="mt-9 inline-block border-b border-primary pb-2 font-bold">Contact the team ↗</Link></Reveal></section>
</main>}
