import type { Metadata } from "next";
import Link from "next/link";
import { Reveal } from "@/components/reveal";

export const metadata: Metadata = { title: "Student Guide", description: "A student guide to FIRST Robotics Competition and the RobotECS season." };
const facts = [["135 lb","maximum robot weight in the standard FRC ruleset"],["12 V","robot battery system used to power motors and electronics"],["3 + 3","three robots per alliance, working with three human-player teams"],["6 weeks","the typical build window teams plan around after Kickoff"]];
export default function StudentPage(){return <main id="main">
  <section className="editorial-hero"><p className="eyebrow">FOR FUTURE BUILDERS / ROBOTECS</p><Reveal><h1>YOUR FIRST<br/><span className="text-primary">SEASON.</span></h1><p>A practical guide to FIRST Robotics Competition, what we will build, and what you will take with you.</p></Reveal></section>
  <section className="grid gap-12 bg-white px-5 py-28 text-black md:grid-cols-[.35fr_1.65fr] md:px-[8vw]"><p className="eyebrow">01 / WHAT IS FRC?</p><div><h2 className="text-5xl font-bold tracking-[-.06em] md:text-7xl">Sport-level energy.<br/>Engineering-level work.</h2><p className="mt-8 max-w-3xl text-lg leading-relaxed text-zinc-700">FIRST Robotics Competition is a high-school program where students design, build, and program an industrial-sized robot for a new game released each January.</p></div></section>
  <section className="px-5 py-28 md:px-[8vw]"><p className="eyebrow">02 / THE ROBOT</p><div className="mt-14 grid gap-8 md:grid-cols-4">{facts.map(([value,copy])=><Reveal key={value}><article className="border-t border-white/20 pt-5"><strong className="text-5xl tracking-[-.06em]">{value}</strong><p className="mt-4 text-sm leading-relaxed text-muted-foreground">{copy}</p></article></Reveal>)}</div></section>
  <section className="grid gap-12 bg-primary px-5 py-28 text-white md:grid-cols-[.75fr_1.25fr] md:px-[8vw]"><div><p className="eyebrow text-white">03 / THIS SEASON</p><h2 className="mt-6 text-6xl font-bold tracking-[-.07em]">What will we build?</h2></div><p className="text-xl leading-relaxed">After Kickoff, we will study the rules, prototype several mechanisms, choose a drive base and scoring strategy, then build the robot that our team can operate reliably.</p></section>
  <section className="px-5 py-28 md:px-[8vw]"><p className="eyebrow">READY?</p><h2 className="mt-6 text-6xl font-bold tracking-[-.07em] md:text-8xl">Bring a question.<br/><span className="text-primary">Leave with a skill.</span></h2><Link href="/contact" className="mt-9 inline-block border-b border-primary pb-2 font-bold">Contact the team ↗</Link></section>
</main>}
